apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-track-core
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-track-core
  template:
    metadata:
      labels:
        app: gym-track-core
    spec:
      serviceAccountName: db-secret-access-service-account
      containers:
        - name: gym-track-core-container
          image: johnjaredprater/gym_track_core:0.5.2
          ports:
            - containerPort: 80
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"