apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-track-core
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym-track-core
  template:
    metadata:
      labels:
        app: gym-track-core
    spec:
      serviceAccountName: secret-service-account
      initContainers:
        - name: alembic-migrate
          image: johnjaredprater/gym_track_core:3.0.0
          command: ["alembic", "upgrade", "head"]
          volumeMounts:
            - name: database-credentials
              mountPath: "/mnt/db-secrets"
              readOnly: true
      containers:
        - name: gym-track-core-container
          image: johnjaredprater/gym_track_core:3.0.0
          ports:
            - containerPort: 80
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/mnt/firebase-config/firebase-key.json"
          volumeMounts:
            - name: database-credentials
              mountPath: "/mnt/db-secrets"
              readOnly: true
            - name: firebase-config
              mountPath: "/mnt/firebase-config"
              readOnly: true
            - name: anthropic-api-key
              mountPath: "/mnt/anthropic-api-key"
              readOnly: true
      volumes:
        - name: database-credentials
          secret:
            secretName: "db-credentials"
        - name: firebase-config
          secret:
            secretName: "firebase-credentials"
        - name: anthropic-api-key
          secret:
            secretName: "anthropic-api-key"
