apiVersion: v1
kind: Service
metadata:
  name: gym-track-core
spec:
  selector:
    app: gym-track-core
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port on the target pod
