"""Exercise and Workout Tables

Revision ID: 5a6e345da6fe
Revises:
Create Date: 2024-11-03 22:20:46.084938

"""

from typing import Sequence, Union

import sqlalchemy
from advanced_alchemy.types import DateTimeUTC

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a6e345da6fe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts", sqlalchemy.Column("date", DateTimeUTC(timezone=True), nullable=True)
    )

    op.execute(
        """
            UPDATE workouts
            SET date = created_at
            WHERE date IS NULL;
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "date")
    # ### end Alembic commands ###
