name: Build

on:
  pull_request:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
          sudo apt update -y
          sudo apt install libmariadb3 libmariadb-dev -y
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
            sudo apt update -y
            sudo apt install libmariadb3 libmariadb-dev -y
            pip install --upgrade pip
            pip install .["test"]
      # - name: Test with pytest
      #   run: |
      #       pytest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: johnjaredprater
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: johnjaredprater/gym_track_core
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
