name: Build & Release

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install .["test"]
      - name: Test with pytest
        run: |
            pytest
      - name: Create Release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # release-type: simple
          release-type: python
          # extra-files: |
          #   deployment.yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: johnjaredprater
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: johnjaredprater/gym_track_core
          tags: |
            ${{ steps.release.outputs.version }}
      - name: Containerize and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kubernetes YAML with new Docker tag
        if: ${{ steps.release.outputs.version != '' }}
        run: .github/update-k8s-tag.sh ${{ steps.release.outputs.version }}
